version: '2'

services:

    #--------------------------------------
    # Web Service
    #--------------------------------------
    imdock-web2pdf:
        restart: always
        image: suwaychang0608/imdock-web2pdf
        container_name: imdock-web2pdf
        working_dir: /app
        ports:
            - "8080:8080"

        volumes:

         - ./pdfout:/app/static/pdfout

networks:
    default:
        external:
            name: imdockgroup
