version: '2'

services:

    #--------------------------------------
    # Web Service
    #--------------------------------------
    imdock-web2pdf:
        restart: always
        image: suwaychang0608/mdock-web2pdf
#        build:
#          context: .
#          dockerfile: Dockerfile
        container_name: web2pdf
        working_dir: /app
        ports:
            - "3380:8080"
#            - "9000:9000"
networks:
    default:
        external:
            name: imdockgroup
